/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.salesagent.controller;import cn.zhuatech.salesagent.common.ApiResponse;import cn.zhuatech.salesagent.service.OutboundActionAuthorizationService;import jakarta.validation.Valid;import org.springframework.web.bind.annotation.*;/**
                                                                                                                                                                                                                                                      * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                      */
@RestController @RequestMapping("/api/enterprise/salesagent")public class OutboundActionAuthorizationController{private final OutboundActionAuthorizationService service;/**
                                                                                                                                                                                                                                                                                                                                                                                                                               * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                               */
public OutboundActionAuthorizationController(OutboundActionAuthorizationService service){this.service=service;}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              */
@PostMapping("/outbound-action-authorization")public ApiResponse<OutboundActionAuthorizationService.Assessment>assess(@Valid @RequestBody OutboundActionAuthorizationService.Request request){return ApiResponse.ok(service.assess(request));}}
