/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.salesagent.service;import org.junit.jupiter.api.Test;import static org.assertj.core.api.Assertions.assertThat;/**
                                                                                                                                   * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                   */
class OutboundActionAuthorizationServiceTest{private final OutboundActionAuthorizationService s=new OutboundActionAuthorizationService();/**
                                                                                                                                                                                                                                                                            * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                            */
@Test void executesGovernedAction(){var r=s.assess(new OutboundActionAuthorizationService.Request("A1",true,true,false,true,true,true,true,true,true,true,true,true));assertThat(r.decision()).isEqualTo(OutboundActionAuthorizationService.Decision.EXECUTE);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           */
@Test void reviewsOperationalGaps(){var r=s.assess(new OutboundActionAuthorizationService.Request("A2",true,true,false,true,true,false,false,false,false,true,false,false));assertThat(r.actions()).hasSize(2);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           */
@Test void blocksUnsafeAction(){var r=s.assess(new OutboundActionAuthorizationService.Request("A3",false,false,true,false,false,true,false,true,false,false,true,true));assertThat(r.blockers()).hasSize(8);}}
